task2 - изменения в проекте логотипов и основного текста
DanSper/first-step pull request #2
Opened 2023-02-12 06:16 UTC by DanSper

1. Добавил новый логотип figma. 
2. Добавил изменения в стилизацию основного текста
3. Постарался использовать методологию BEM.
4. Сделал поправки под код стайлу.

2023-02-12 09:38 UTC, m777553 requested changes

2023-02-12 09:38 UTC, m777553 commented on index.html
> +			<img class="imgs imgs--big" src="./images/Clean_man.jpg"   height: 387px  width: 943px>
height: 387px width: 943px удаляем

2023-02-12 09:38 UTC, m777553 commented on index.html
> +				<img src="./images/text_adobe_photoshop.svg" class="adobe_photoshop">
Не хватает обязательного для img атрибута

2023-02-12 09:38 UTC, m777553 commented on style.css
>  .denis, h1 p{
ищем как обнулять базовые стили через отдельный файл

2023-02-12 09:38 UTC, m777553 commented on style.css
> +	margin-left: -40px;
Плохая практика  - отрицательный маргин

2023-02-12 09:38 UTC, m777553 commented on style.css
> +	width: 766px;
лучше указывать height: auto

2023-02-12 09:38 UTC, m777553 commented on style.css
> +	width: 766px;
так со всеми изображениями

2023-02-12 09:38 UTC, m777553 commented on style.css
> +	left: 1px;
Left тут не используется

2023-02-12 09:38 UTC, m777553 commented on style.css
> +	left: 1px;
и далее

2023-02-18 14:52 UTC, m777553 commented on asserts/fonts/Gilroy-Bold/style.css
> +@font-face {
тут и в другом файле стилей одинаковые описания?

2023-02-18 14:53 UTC, m777553 commented on style.css
> +	transform: rotate(270deg);
```suggestion
	transform: rotate(-90deg);
```

2023-02-18 15:07 UTC, m777553 commented on style.css
> +	width: 1445px;
зачем тут фиксированная ширина?

2023-02-18 15:10 UTC, m777553 commented on index.html
> +						<a href="#"><img src="./asserts/images/logo_adobe_photoshop.svg" class="item__logo" alt="adobe photoshop logo"></a>
почему только картинка ссылка? лучше ссылкой делать и картинку и надпись

2023-02-19 12:47 UTC, m777553 commented on style.css
> +﻿@font-face {
asserts/fonts/Gilroy-Bold/style.css
а тут тогда что за шрифты?

2023-02-19 12:48 UTC, m777553 commented on style.css
> +	margin-left: -40px;  /*!!! исправить! */
Жду

2023-02-19 17:03 UTC, DanSper commented on style.css
> +	transform: rotate(270deg);
Я поменял значение, но ничего не изменилось

2023-02-19 17:03 UTC, DanSper commented on style.css
> +	width: 1445px;
Сделать 100% ?

2023-02-19 17:03 UTC, DanSper commented on style.css
> +	width: 1445px;
Тест

2023-02-19 17:03 UTC, DanSper commented on asserts/fonts/Gilroy-Bold/style.css
> +@font-face {
add

2023-02-19 17:05 UTC, DanSper commented on asserts/fonts/Gilroy-Bold/style.css
> +@font-face {
next

2023-02-19 17:06 UTC, DanSper commented on index.html
> -			<li><a href="#">Contacts</a></li>
remove

2023-02-19 17:41 UTC, DanSper commented on index.html
> +					<p class="item__vertical"><a href="#"><span class="item__vertical item__vertical--button-color-ru"> ru</span></a><a href="#"> |
item__vertical--button-color-ru
За что отвечает этот стиль? По названию он закреплен за языком, но не в этом его назначение

2023-02-19 17:44 UTC, DanSper commented on style.css
> +	font-family: Gilroy-Bold;
когда используем кастомные шрифты, обязательно добавляй альтернативу из распространенных и семейство шрифтов

2023-02-21 13:49 UTC, merged